// fonts.h — Space Grotesk for text on the pad (docs/style-guide.md,
// "Typography"). Generated by tools/make_fonts.js; don't edit the .c files.
//
// These hold text only: Latin-1 plus – — ‘ ’ “ ” • … − €. Icons use LVGL's
// built-in Montserrat symbol fonts.
#pragma once

#include <lvgl.h>

LV_FONT_DECLARE(space_grotesk_regular_12)   // status bar, menu captions
LV_FONT_DECLARE(space_grotesk_regular_14)   // menu text
LV_FONT_DECLARE(space_grotesk_medium_14)    // tile labels, compact grid
LV_FONT_DECLARE(space_grotesk_medium_16)    // tile labels, regular grid
LV_FONT_DECLARE(space_grotesk_medium_20)    // menu title
