# embed_web.py — PlatformIO pre-build script: gzip web/ into the firmware.
#
# Writes src/web/web_assets.h with one byte array per file (stored in flash),
# its URL path and content type, and a build hash used as the ETag. The device
# serves these bytes as they are: it never compresses anything itself
# (docs/architecture.md, "Web app delivery").
#
# Runs automatically on every build (extra_scripts in platformio.ini). You can
# also run it by hand: python tools/embed_web.py

import gzip
import hashlib
import os

try:
    Import("env")  # noqa: F821 — provided by PlatformIO
    ROOT = env["PROJECT_DIR"]  # noqa: F821
except NameError:
    ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

WEB_DIR = os.path.join(ROOT, "web")
OUT_PATH = os.path.join(ROOT, "src", "web", "web_assets.h")

# Development-only files stay out of the firmware.
SKIP = {"test.html", "test.js", "mock-device.js"}

TYPES = {
    ".html": "text/html; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".svg": "image/svg+xml",
    ".woff2": "font/woff2",
    ".json": "application/json",
}


def collect():
    files = []
    for folder, _, names in os.walk(WEB_DIR):
        for name in sorted(names):
            if name in SKIP:
                continue
            ext = os.path.splitext(name)[1]
            if ext not in TYPES:
                continue
            full = os.path.join(folder, name)
            url = "/" + os.path.relpath(full, WEB_DIR).replace(os.sep, "/")
            files.append((url, full, TYPES[ext]))
    return sorted(files)


def main():
    assets = []
    digest = hashlib.sha1()
    for url, full, ctype in collect():
        with open(full, "rb") as f:
            raw = f.read()
        # mtime=0 keeps the output identical for identical input.
        body = raw if url.endswith(".woff2") else gzip.compress(raw, 9, mtime=0)
        digest.update(url.encode() + body)
        assets.append((url, ctype, body, not url.endswith(".woff2")))

    lines = [
        "// web_assets.h — GENERATED by tools/embed_web.py from web/. Do not edit.",
        "#pragma once",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "struct WebAsset {",
        "    const char*    path;      // URL path, e.g. \"/app.js\"",
        "    const char*    type;      // Content-Type",
        "    const uint8_t* data;",
        "    size_t         size;",
        "    bool           gzipped;   // send with Content-Encoding: gzip",
        "};",
        "",
        'static const char* const WEB_BUILD_HASH = "%s";' % digest.hexdigest()[:12],
        "",
    ]
    for i, (url, _, body, _) in enumerate(assets):
        lines.append("// %s (%d bytes)" % (url, len(body)))
        lines.append("static const uint8_t kAsset%d[] = {" % i)
        for start in range(0, len(body), 20):
            chunk = body[start:start + 20]
            lines.append("    " + ", ".join("0x%02X" % b for b in chunk) + ",")
        lines.append("};")
        lines.append("")
    lines.append("static const WebAsset kWebAssets[] = {")
    for i, (url, ctype, body, gz) in enumerate(assets):
        lines.append('    {"%s", "%s", kAsset%d, sizeof(kAsset%d), %s},'
                     % (url, ctype, i, i, "true" if gz else "false"))
    lines.append("};")
    lines.append("static const size_t kWebAssetCount = sizeof(kWebAssets) / sizeof(kWebAssets[0]);")
    text = "\n".join(lines) + "\n"

    # Only rewrite when something changed, so PlatformIO doesn't rebuild for nothing.
    old = None
    if os.path.exists(OUT_PATH):
        with open(OUT_PATH, "r", encoding="utf-8") as f:
            old = f.read()
    if old != text:
        os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
        with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
    total = sum(len(a[2]) for a in assets)
    print("embed_web: %d files, %.1f KB compressed" % (len(assets), total / 1024))


main()
