// make_icons.js — draw the web editor's SVG icons (web/lib/icons.js) as
// LVGL images, so the pad shows exactly what the editor previews.
//   node tools/make_icons.js
// Writes src/ui/icon_images.c: one A8 (alpha-only) image per icon and size.
// The tile colours an A8 image with its accent colour when drawing it.
// Needs @resvg/resvg-js; installed on first run into .pio/node-tools/.
'use strict';

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const { ROOT, loadTG } = require('./web_lib');

// Style guide, "Icons": 20 px on the regular grid, 18 px on compact.
const SIZES = [20, 18];

function loadResvg() {
  const dir = path.join(ROOT, '.pio', 'node-tools');
  const mod = path.join(dir, 'node_modules', '@resvg', 'resvg-js');
  if (!fs.existsSync(mod)) {
    console.log('installing @resvg/resvg-js into .pio/node-tools');
    execFileSync('npm', ['install', '--prefix', dir, '--no-audit', '--no-fund', '@resvg/resvg-js@2'],
      { stdio: 'inherit', shell: process.platform === 'win32' });   // npm is a .cmd on Windows
  }
  return require(mod).Resvg;
}

// One icon as alpha bytes (0 = transparent, 255 = solid), row by row.
function rasterize(Resvg, body, size) {
  // Same attributes as the editor's <svg class="i">: 1.8 stroke, round caps.
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" width="${size}" height="${size}"
    fill="none" stroke="white" color="white" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${body}</svg>`;
  const img = new Resvg(svg, { fitTo: { mode: 'width', value: size } }).render();
  const alpha = Buffer.alloc(size * size);
  for (let i = 0; i < size * size; i++) alpha[i] = img.pixels[i * 4 + 3];
  return alpha;
}

function main() {
  const Resvg = loadResvg();
  const TG = loadTG();
  const lines = [
    '// icon_images.c — GENERATED by tools/make_icons.js from web/lib/icons.js. Do not edit.',
    '// A8 images: the tile draws them in its accent colour.',
    '',
    '#include "lvgl.h"',
    '',
  ];
  const table = {};
  for (const size of SIZES) table[size] = [];

  TG.ICONS.forEach(([name, body], i) => {
    for (const size of SIZES) {
      const id = `icon_${name}_${size}`;
      const alpha = rasterize(Resvg, body, size);
      lines.push(`static const uint8_t ${id}_map[] = {`);
      for (let row = 0; row < size; row++) {
        lines.push('    ' + [...alpha.subarray(row * size, row * size + size)].map((b) => '0x' + b.toString(16).padStart(2, '0')).join(', ') + ',');
      }
      lines.push('};');
      lines.push(`static const lv_image_dsc_t ${id} = {`);
      lines.push(`    .header = {.magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_A8, .w = ${size}, .h = ${size}, .stride = ${size}},`);
      lines.push(`    .data_size = sizeof(${id}_map),`);
      lines.push(`    .data = ${id}_map,`);
      lines.push('};');
      lines.push('');
      table[size][i + 1] = `&${id}`;
    }
  });

  // Lookup by icon number (0 = none), one table per size.
  for (const size of SIZES) {
    const entries = ['NULL'].concat(TG.ICONS.map((_, i) => table[size][i + 1]));
    lines.push(`const lv_image_dsc_t* const icon_images_${size}[] = {`);
    entries.forEach((e, i) => lines.push(`    ${e},   /* ${i} ${i ? TG.ICONS[i - 1][0] : 'none'} */`));
    lines.push('};');
    lines.push('');
  }
  lines.push(`const unsigned icon_image_count = ${TG.ICONS.length + 1};`);

  const out = path.join(ROOT, 'src', 'ui', 'icon_images.c');
  fs.writeFileSync(out, lines.join('\n') + '\n');
  console.log(`wrote src/ui/icon_images.c (${TG.ICONS.length} icons × ${SIZES.join(', ')} px)`);
}

main();
